language: rust
rust:
    - stable
    - beta
    - nightly
notifications:
    email:
        - evrey@hackish.codes
before_script:
    - rustc --version
    - cargo --version
branches:
    only:
        - master
