[package]
name = "rsgba"
version = "0.1.0"
authors = ["Evrey <evrey@hackish.codes>"]

[dependencies]
clippy = { version = "^0.0", optional = true }
log = "^0.3"
argparse = "^0.2"
byteorder = "^0.4"

[features]
default = []
